import test from "node:test";import assert from "node:assert/strict";import {discoverWallets,connectWallet,assertWallet} from "../lib/wallet.ts";
const address="0x"+"11".repeat(20);
test("Rabby connects through standard EIP-1193 without MetaMask Snap",async()=>{let chain="0x1";const methods=[];const p={isRabby:true,async request({method,params}){methods.push(method);if(method==="eth_requestAccounts"||method==="eth_accounts")return [address];if(method==="eth_chainId")return chain;if(method==="wallet_switchEthereumChain"){chain=params[0].chainId;return null}throw new Error("Unexpected "+method)}};const s=await connectWallet({id:"rabby",name:"Rabby",provider:p});assert.equal(s.address,address);assert.equal(chain,"0xf22d");assert.equal(methods.some(m=>m.startsWith("wallet_")&&m.includes("Snap")),false)});
test("changed signing account is refused",async()=>{await assert.rejects(assertWallet({address,provider:{request:async()=>["0x"+"22".repeat(20)]}}),/account changed/)});
test("wallet discovery retains independently announced wallets",async()=>{const target=new EventTarget();const p1={request:async()=>null},p2={request:async()=>null};target.addEventListener("eip6963:requestProvider",()=>{for(const [id,p] of [["one",p1],["two",p2]])target.dispatchEvent(new CustomEvent("eip6963:announceProvider",{detail:{info:{uuid:id,name:id},provider:p}}))});globalThis.window=Object.assign(target,{ethereum:p1});try{const list=await discoverWallets();assert.equal(list.length,2);assert.equal(list[1].provider,p2)}finally{delete globalThis.window}});

test("Rabby's announced provider replaces its separate legacy proxy",async()=>{const target=new EventTarget(),rabby={request:async()=>null},okx={request:async()=>null},proxy={isRabby:true,isMetaMask:true,request:async()=>null};target.addEventListener("eip6963:requestProvider",()=>{for(const [uuid,name,provider] of [["r","Rabby Wallet",rabby],["o","OKX Wallet",okx]])target.dispatchEvent(new CustomEvent("eip6963:announceProvider",{detail:{info:{uuid,name},provider}}))});globalThis.window=Object.assign(target,{ethereum:proxy});try{const list=await discoverWallets();assert.deepEqual(list.map(w=>w.name),["Rabby Wallet","OKX Wallet"]);assert.equal(list[0].provider,rabby)}finally{delete globalThis.window}});
for(const error of [{code:4902},{code:-32603,data:{originalError:{code:4902}}},{code:-32603,message:'Unrecognized chain ID "0xf22d". Try adding the chain using wallet_switchEthereumChain first.'}]){
 test("missing Studio Next network is added then switched: "+JSON.stringify(error),async()=>{let chain="0x1",added=false;const methods=[];const provider={async request({method,params}){methods.push(method);if(method==="eth_requestAccounts"||method==="eth_accounts")return [address];if(method==="eth_chainId")return chain;if(method==="wallet_switchEthereumChain"){if(!added)throw error;chain=params[0].chainId;return null}if(method==="wallet_addEthereumChain"){assert.equal(params[0].chainId,"0xf22d");assert.deepEqual(params[0].rpcUrls,["https://studio-next.genlayer.com/api"]);assert.equal(params[0].nativeCurrency.decimals,18);assert.ok(params[0].blockExplorerUrls[0]);added=true;return null}throw Error(method)}};await connectWallet({id:"r",name:"Rabby",provider});assert.equal(chain,"0xf22d");assert.deepEqual(methods.filter(m=>m.startsWith("wallet_")),["wallet_switchEthereumChain","wallet_addEthereumChain","wallet_switchEthereumChain"])});
}
test("canceling a network switch never requests a network addition",async()=>{const methods=[];const provider={async request({method}){methods.push(method);if(method==="eth_requestAccounts")return [address];if(method==="eth_chainId")return "0x1";throw {code:4001,message:"User rejected unknown chain request"}}};await assert.rejects(connectWallet({id:"r",name:"Rabby",provider}));assert.equal(methods.includes("wallet_addEthereumChain"),false)});
test("rejected network addition stops without retrying",async()=>{const methods=[];const provider={async request({method}){methods.push(method);if(method==="eth_requestAccounts")return [address];if(method==="eth_chainId")return "0x1";if(method==="wallet_switchEthereumChain")throw {code:4902};throw {code:4001}}};await assert.rejects(connectWallet({id:"r",name:"Rabby",provider}));assert.equal(methods.filter(m=>m==="wallet_switchEthereumChain").length,1)});
