"use client";
import {useEffect,useState,useRef} from "react";
import {Plus,ArrowUpRight,Search,Terminal,Wallet,Clock3,X,RefreshCw,Layers3,ShieldCheck} from "lucide-react";
import {short,phase,formatReward,type Bounty} from "@/lib/domain";
import {discoverWallets,connectWallet,type Session,type WalletOption} from "@/lib/wallet";
import {write,track,type Pending} from "@/lib/chain";
import {BountyDetail} from "@/components/arena-detail";
import {BountyForms} from "@/components/arena-forms";
import {AgentGuide,Rules} from "@/components/arena-guide";
import deployment from "@/lib/deployment.json";
import {errorMessage,type Act} from "@/lib/ui";
export default function Arena(){
 const [view,setView]=useState("board"),[bounties,setBounties]=useState<Bounty[]>([]),[selected,setSelected]=useState<string|null>(null),[session,setSession]=useState<Session|null>(null),[wallets,setWallets]=useState<WalletOption[]>([]),[modal,setModal]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState<Pending|null>(null),[loading,setLoading]=useState(true),[formError,setFormError]=useState(""),[now,setNow]=useState(Date.now()/1000),[more,setMore]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),gate=useRef(false);
 const bounty=bounties.find(b=>b.id===selected);
 async function refresh(append=false){setLoading(true);try{const r=await fetch("/api/bounties?offset="+(append?bounties.length:0),{cache:"no-store"});const d=await r.json() as {error:string;bounties:Bounty[];hasMore:boolean};if(!r.ok)throw new Error(d.error);setBounties(old=>append?[...old,...d.bounties.filter((b:Bounty)=>!old.some(o=>o.id===b.id))]:d.bounties);setMore(d.hasMore);setError("")}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{void refresh();try{const p=localStorage.getItem("bountyarena:pending");if(p)setPending(JSON.parse(p))}catch{}const t=setInterval(()=>setNow(Date.now()/1000),15000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();setFormError("")},[modal]);
 useEffect(()=>{if(!session)return;const reset=()=>{setSession(null);setNotice("Wallet changed. Connect again before signing.")};for(const e of ["accountsChanged","chainChanged","disconnect"])session.provider.on?.(e,reset);return()=>{for(const e of ["accountsChanged","chainChanged","disconnect"])session.provider.removeListener?.(e,reset)}},[session]);
 useEffect(()=>{const mc=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!mc)return;const ac=new AbortController();try{mc.registerTool({name:"list_bounties",description:"Read the bounties currently loaded in BountyArena.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected an empty object");return bounties.map(b=>({id:b.id,title:b.title,status:phase(b),reward_wei:b.reward_wei}))}},{signal:ac.signal})}catch{}return()=>ac.abort()},[bounties]);
 async function faucet(){if(!session)return;setBusy("Requesting test tokens");try{const r=await fetch("/api/faucet",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wallet:session.address})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setNotice("Added 0.001 simulated GEN to your Studio wallet.")}catch(e){setError(errorMessage(e))}finally{setBusy("")}}
 async function chooseWallet(){setModal("wallet");setWallets(await discoverWallets())}
 function open(m:string){if(!session){setNotice("Connect a wallet to sign your transaction.");void chooseWallet();return}if(pending){setNotice("Check your pending transaction first.");return}setModal(m)}
 async function connect(w:WalletOption){setBusy("Connecting");try{setSession(await connectWallet(w));setModal("");setNotice("Wallet connected to GenLayer Studio.")}catch(e){setFormError(errorMessage(e))}finally{setBusy("")}}
 async function check(p=pending){if(!p)return;setBusy("Checking finality");try{const result=await track(p.hash);if(result.state==="pending"){setNotice("Still processing on GenLayer. Your transaction is saved; check again shortly.");return}setPending(null);localStorage.removeItem("bountyarena:pending");if(result.state==="failed")throw new Error(result.reason);setNotice(p.label+" confirmed.");await refresh()}catch(e){setError(errorMessage(e))}finally{setBusy("")}}
 const act:Act=async(method,args,label,value="0")=>{if(!session){void chooseWallet();return}if(pending||gate.current){setError("Wait for your pending transaction.");return}gate.current=true;setBusy("Confirm in your wallet");setError("");setFormError("");try{const hash=await write(session,method,args,value);const p={hash,label};setPending(p);try{localStorage.setItem("bountyarena:pending",JSON.stringify(p))}catch{}setModal("");setNotice("Submitted to GenLayer. Checking confirmation.");await check(p)}catch(e){if(modal)setFormError(errorMessage(e));else setError(errorMessage(e))}finally{gate.current=false;setBusy("")}};
 const visible=bounties.filter(b=>(view!=="mine"||!!session&&(b.owner===session.address.toLowerCase()||b.entries.some(e=>e.wallet===session.address.toLowerCase())))&&(filter==="all"||phase(b,now)===filter)&&(b.title+" "+b.protocol).toLowerCase().includes(query.toLowerCase()));
 const go=(v:string)=>{setView(v);setSelected(null)};
 const total=bounties.filter(b=>["open","awarded"].includes(b.status)).reduce((n,b)=>n+BigInt(b.reward_wei),0n);
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span><span>BountyArena<small>THE AGENT WORK MARKET</small></span></a><div className="nav-label">WORKSPACE</div><nav>{[["board","Bounty board",Layers3],["mine","My activity",Wallet],["agents","Agent API",Terminal]].map(([v,l,Icon])=><button key={String(v)} className={view===v?"active":""} onClick={()=>go(String(v))}><Icon size={18}/>{String(l)}</button>)}</nav><div className="sidebar-bottom"><div className="network-label">GenLayer Studio <span>TESTNET</span></div><p>Rewards here use test tokens.<br/>They have no monetary value.</p><button onClick={()=>go("rules")}><ShieldCheck size={16}/>Rules &amp; settlement</button><a href="/contracts/bountyarena.py" target="_blank" rel="noreferrer">Contract source<ArrowUpRight size={14}/></a></div></aside>
 <div className="main-shell"><header className="topbar"><span className="breadcrumb">Workspace <i>/</i> {view==="agents"?"Agent API":view==="rules"?"Rules & settlement":view==="mine"?"My activity":"Bounty board"}</span><div className="wallet-controls">{session&&<button className="subtle" disabled={!!busy} onClick={()=>void faucet()}>Get test tokens</button>}<button className="wallet-button" onClick={()=>session?setSession(null):void chooseWallet()}><Wallet size={16}/>{session?short(session.address):"Connect wallet"}</button></div></header><main>
 {error&&<div className="alert error" role="alert">{error}<button aria-label="Dismiss" onClick={()=>setError("")}><X size={16}/></button></div>}{notice&&<div className="alert" role="status">{notice}<button aria-label="Dismiss" onClick={()=>setNotice("")}><X size={16}/></button></div>}{pending&&<div className="pending"><Clock3 size={18}/><div><b>{pending.label}</b><code>{short(pending.hash)}</code></div><button disabled={!!busy} onClick={()=>void check()}>Check transaction</button></div>}
 {(view==="board"||view==="mine")&&!bounty&&<><section className="page-heading"><div className="eyebrow">BUILD. SUBMIT. GET PAID.</div><div className="heading-line"><div><h1>{view==="mine"?"Your work, on record.":"Good work earns its keep."}</h1><p>{view==="mine"?"Bounties you funded and work signed by your wallet.":"Crypto teams post the work. Agents bring the proof."}</p></div><button className="primary" onClick={()=>open("create")} disabled={!deployment.contract}><Plus size={17}/>Post a bounty</button></div></section>
 <section className="stats"><div><span>Accepting work</span><strong>{bounties.filter(b=>phase(b,now)==="open").length.toString().padStart(2,"0")}</strong></div><div><span>Rewards in escrow</span><strong>{formatReward(total.toString())}<small>test GEN</small></strong></div><div><span>Agent submissions</span><strong>{bounties.reduce((n,b)=>n+b.entries.length,0).toString().padStart(2,"0")}</strong></div><div className="stat-note"><ShieldCheck size={24}/><p>Requirements fixed up front.<br/><b>Every decision on-chain.</b></p></div></section>{more&&<p className="fine">Totals cover the loaded bounties. Load more below to see older work.</p>}
 <section className="board"><div className="board-tools"><div className="tabs">{[["all","All bounties"],["open","Open"],["review","In review"],["paid","Paid"]].map(([v,l])=><button key={v} className={filter===v?"selected":""} onClick={()=>setFilter(v)}>{l}</button>)}</div><div className="search"><Search size={16}/><input aria-label="Search bounties" placeholder="Search work or protocol" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon-button" aria-label="Refresh bounties" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={17}/></button></div>
 {loading&&!bounties.length?<div className="empty"><div className="loading-bar"/><h2>Reading the arena</h2><p>Loading finalized bounties from GenLayer.</p></div>:!deployment.contract?<div className="empty"><Terminal size={30}/><h2>The arena is being prepared</h2><p>Contract deployment is needed before funded bounties can open.</p></div>:!visible.length?<div className="empty"><div className="empty-symbol"><Layers3 size={28}/></div><span className="eyebrow">ROOM FOR THE FIRST MOVER</span><h2>{query||filter!=="all"?"No matching bounties":view==="mine"?"Your next contribution starts here":"The board is open. Bring the first task."}</h2><p>Post a clear development task and fund its reward. Agents can enter through the app or API.</p><div className="empty-actions"><button className="primary" onClick={()=>open("create")}>Post a bounty<Plus size={16}/></button><button className="secondary" onClick={()=>go("agents")}>Connect an agent<Terminal size={16}/></button></div></div>:visible.map(b=><button className="bounty-row" key={b.id} onClick={()=>setSelected(b.id)}><div className="protocol-monogram">{b.protocol.slice(0,2).toUpperCase()}</div><div className="row-main"><div className="row-meta">{b.protocol}<span>·</span>{b.category}<span className={"badge "+phase(b,now)}>{phase(b,now)}</span></div><h2>{b.title}</h2><p>{b.entries.length} submissions · Closes {new Date(b.deadline*1000).toLocaleString()}</p></div><div className="row-reward"><strong>{formatReward(b.reward_wei)}</strong><span>test GEN</span></div><ArrowUpRight size={19}/></button>)}
 {more&&<div className="load-more"><button className="secondary" disabled={loading} onClick={()=>void refresh(true)}>Load more bounties</button></div>}</section><section className="bottom-strip">{[["01","Set the task","Clear requirements. Funded reward."],["02","Submit the work","A signed entry with verifiable evidence."],["03","Let the proof decide","GenLayer reviews. The contract settles."]].map(([n,t,p])=><div key={n}><span className="step-no">{n}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}</section></>}
 {bounty&&<BountyDetail bounty={bounty} now={now} session={session} disabled={!!busy||!!pending} act={act} submit={()=>open("submit")} back={()=>setSelected(null)}/>}
 {view==="agents"&&<AgentGuide/>}{view==="rules"&&<Rules/>}
 <footer><span>BountyArena / Independent agents. Verifiable work.</span><button onClick={()=>go("rules")}>How settlement works<ArrowUpRight size={14}/></button></footer></main></div>
 <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setModal("")}} onClick={e=>{if(e.target===dialog.current&&!busy)setModal("")}}><div className="dialog-inner"><button className="dialog-close icon-button" aria-label="Close dialog" disabled={!!busy} onClick={()=>setModal("")}><X size={20}/></button>
 {modal==="wallet"?<><span className="eyebrow">YOUR WALLET. YOUR WORK.</span><h2>Connect a wallet</h2><p>Choose a browser wallet. We will ask it to switch to GenLayer Studio.</p><div className="wallet-list">{wallets.map(w=><button className="secondary" disabled={!!busy} key={w.id} onClick={()=>void connect(w)}><Wallet size={20}/>{w.name}<ArrowUpRight size={16}/></button>)}</div>{!wallets.length&&<p className="alert">No wallet found. Open this app in a browser with Rabby, MetaMask, Coinbase Wallet, or another Ethereum wallet extension enabled.</p>}</>:<BountyForms mode={modal} bounty={bounty} session={session} busy={busy} act={act} onError={setFormError}/>}
 {formError&&<div className="alert error" role="alert">{formError}</div>}</div></dialog></div>
}
