import {useState} from "react";
import {Plus,X,ArrowUpRight} from "lucide-react";
import {bountySchema,submissionSchema,type Bounty} from "@/lib/domain";
import type {Session} from "@/lib/wallet";
import {errorMessage,type Act} from "@/lib/ui";
export function BountyForms({mode,bounty,session,busy,act,onError}:{mode:string;bounty?:Bounty;session:Session|null;busy:string;act:Act;onError:(e:string)=>void}){
 const [criteria,setCriteria]=useState([""]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{const b=bountySchema.parse({id:crypto.randomUUID(),title:fd.get("title"),protocol:fd.get("protocol"),category:fd.get("category"),requirements:criteria,duration:Number(fd.get("duration")),reward:fd.get("reward")});const {parseEther}=await import("viem");await act("create_bounty",[b.id,b.title,b.protocol,b.category,JSON.stringify(b.requirements),b.duration],"Bounty funded",parseEther(b.reward).toString())}catch(e){onError(errorMessage(e))}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!session||!bounty)return;const fd=new FormData(e.currentTarget);try{const s=submissionSchema.parse({wallet:session.address,agent:fd.get("agent"),summary:fd.get("summary"),evidence:fd.get("evidence")});await act("submit_work",[bounty.id,s.agent,s.summary,s.evidence],"Submission recorded")}catch(e){onError(errorMessage(e))}}
 if(mode==="create")return <form onSubmit={create}><span className="eyebrow">PUT THE REWARD BEHIND THE WORK</span><h2>Post a bounty</h2><label>Task title<input name="title" required minLength={8} maxLength={120} placeholder="Write an ethers v6 integration guide"/></label><div className="form-row"><label>Protocol or project<input name="protocol" required minLength={2} maxLength={50} placeholder="Your protocol"/></label><label>Type of work<select name="category"><option>Documentation</option><option>Integration</option><option>Migration</option></select></label></div><fieldset><legend>Acceptance requirements</legend><p className="fine">Be specific. Every requirement must be verifiable from the evidence file.</p>{criteria.map((c,i)=><div className="criterion-input" key={i}><span>{i+1}</span><textarea required minLength={10} maxLength={400} value={c} onChange={e=>setCriteria(criteria.map((v,j)=>j===i?e.target.value:v))} placeholder="Include a connection example with network settings and error handling."/>{criteria.length>1&&<button type="button" className="icon-button" aria-label={"Remove requirement "+(i+1)} onClick={()=>setCriteria(criteria.filter((_,j)=>j!==i))}><X size={16}/></button>}</div>)}{criteria.length<5&&<button type="button" className="subtle" onClick={()=>setCriteria([...criteria,""])}><Plus size={15}/>Add requirement</button>}</fieldset><div className="form-row"><label>Reward · test GEN<input name="reward" defaultValue="0.0001" inputMode="decimal" required/></label><label>Submissions close in<select name="duration" defaultValue="86400"><option value="600">10 minutes · quick test</option><option value="3600">1 hour</option><option value="86400">1 day</option><option value="259200">3 days</option><option value="604800">7 days</option></select></label></div><p className="fine">Your reward is escrowed immediately. After closing, entries have a 72-hour review window. The earliest fully qualified entry wins. Maximum 40 entries per bounty.</p><button className="primary full" disabled={!!busy}>{busy||"Fund & post bounty"}<Plus size={17}/></button></form>;
 if(mode==="submit")return <form onSubmit={submit}><span className="eyebrow">LET THE WORK SPEAK</span><h2>Submit your work</h2><p>{bounty?.title}</p><label>Agent or contributor name<input name="agent" required minLength={2} maxLength={60} placeholder="Your agent's name"/></label><label>What did you deliver?<textarea name="summary" required minLength={30} maxLength={4000} rows={5} placeholder="Explain the solution and how it meets each requirement."/></label><label>Evidence file · pinned GitHub URL<input name="evidence" type="url" required placeholder="https://raw.githubusercontent.com/owner/repo/commit/file.md"/></label><p className="fine">Use the full 40-character commit SHA, not main or a tag. Open your file on GitHub, press Y for its permanent link, then select Raw. One entry per wallet; entries cannot be edited. Sponsors cannot enter their own bounty.</p><button className="primary full" disabled={!!busy}>{busy||"Sign & submit work"}<ArrowUpRight size={17}/></button></form>;
 return null;
}
